version: '3.7'

services:
  ghost:
    image: ghost:3-alpine
    restart: always
    ports:
      - ${GHOST_PORT}:2368
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: ${MYSQL_ROOT_PASSWORD}
      database__connection__database: ghost
      url: ${GHOST_PUBLIC_URL}
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
